# Class 2: pandas Data Wrangling for R Users

**Course:** Data 201-Class 2  
**Background assumed:** R, dplyr pipelines, basic data.frames

---

### How to use this notebook
- Run cells **top to bottom**.
- Complete all **TODO** sections.
- When R code is shown, **translate it to pandas**.
- Focus on clarity and correctness.

## 0. Setup

In [ ]:
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 20)

## 1. From data.frame to DataFrame

In R you might do:
```r
df <- read.csv("data.csv")
```

For today we create a small example dataset.

In [ ]:
dt = pd.read_csv("https://raw.githubusercontent.com/Reben80/Data201/refs/heads/main/Dataset/housing.csv")

In [ ]:
data = {
    "price": [200, 180, 250, 300, np.nan, 220, 260],
    "size": [1400, 1200, 1600, 1800, 1500, 1550, 1700],
    "bedrooms": [3, 2, 3, 4, 3, 3, 4],
    "neighborhood": ["A", "A", "B", "B", "A", "B", "B"],
}

df = pd.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         6 non-null      float64
 1   size          7 non-null      int64
 2   bedrooms      7 non-null      int64
 3   neighborhood  7 non-null      object
dtypes: float64(1), int64(2), object(1)
memory usage: 356.0+ bytes

**TODO:**  
1. Check the **dimensions** of `df`  
2. **Inspect** the structure of `df`  
3. Produce **summary statistics**

In [ ]:
df.shape
# 0 = number of rows; 1 = columns
df.columns

Index(['price', 'size', 'bedrooms', 'neighborhood'], dtype='object')

## 2. Index vs Columns (Very Important!)

**TODO:**  
1. Inspect `df.index`  
2. Inspect `df.columns`  

**Question:** Why is the index *not* the same as a regular column?

In [ ]:
# Your code here
df.index

RangeIndex(start=0, stop=7, step=1)

## 3. Selecting Columns (dplyr::select)

In R:
```r
select(df, price, size)
```

**TODO:**  
1. Select only `price` and `size`  
2. Select a single column (`price`) as a **Series**

In [ ]:
# Your code here
df["price"]
df[["price", "size"]]

   price  size
0  200.0  1400
1  180.0  1200
2  250.0  1600
3  300.0  1800
4    NaN  1500
5  220.0  1550
6  260.0  1700

## 4. Filtering Rows (dplyr::filter)

In R:
```r
filter(df, price > 200)
```

**TODO:**  
1. Filter rows where `price > 200`  
2. Filter rows where `price > 200` **and** `bedrooms >= 3`

In [ ]:
# Your code here
df[df["price"]> 200]

   price  size  bedrooms neighborhood
2  250.0  1600         3            B
3  300.0  1800         4            B
5  220.0  1550         3            B
6  260.0  1700         4            B

In [ ]:
df[(df["price"]> 200) & (df["bedrooms"] >= 3)]

   price  size  bedrooms neighborhood
2  250.0  1600         3            B
3  300.0  1800         4            B
5  220.0  1550         3            B
6  260.0  1700         4            B

In [ ]:
df[(df["price"] >200) & (df["price"] <100)]

Empty DataFrame
Columns: [price, size, bedrooms, neighborhood]
Index: []

In [ ]:
df[df["price"]!= 200]

   price  size  bedrooms neighborhood
1  180.0  1200         2            A
2  250.0  1600         3            B
3  300.0  1800         4            B
4    NaN  1500         3            A
5  220.0  1550         3            B
6  260.0  1700         4            B

In [ ]:
df[df["neighborhood"] == "A"]

   price  size  bedrooms neighborhood
0  200.0  1400         3            A
1  180.0  1200         2            A
4    NaN  1500         3            A

In [ ]:
df.query("price >200 and size > 1000")

   price  size  bedrooms neighborhood
2  250.0  1600         3            B
3  300.0  1800         4            B
5  220.0  1550         3            B
6  260.0  1700         4            B

## 5. Creating New Variables (dplyr::mutate)

In R:
```r
mutate(df, price_per_sqft = price / size)
```

**TODO:** Create a new column `price_per_sqft`.

In [ ]:
# Your code here
df.assign(price_persqft = lambda d: d.price/d.size)

   price  size  bedrooms neighborhood  price_persqft
0  200.0  1400         3            A       7.142857
1  180.0  1200         2            A       6.428571
2  250.0  1600         3            B       8.928571
3  300.0  1800         4            B      10.714286
4    NaN  1500         3            A            NaN
5  220.0  1550         3            B       7.857143
6  260.0  1700         4            B       9.285714

In [ ]:
#another way to mutate in python
df["square feet"] = df["size"]/df["price"]
print(df["square feet"])
print(df)

0    7.000000
1    6.666667
2    6.400000
3    6.000000
4         NaN
5    7.045455
6    6.538462
Name: square feet, dtype: float64
   price  size  bedrooms neighborhood  square feet
0  200.0  1400         3            A     7.000000
1  180.0  1200         2            A     6.666667
2  250.0  1600         3            B     6.400000
3  300.0  1800         4            B     6.000000
4    NaN  1500         3            A          NaN
5  220.0  1550         3            B     7.045455
6  260.0  1700         4            B     6.538462

## 6. Sorting Rows (dplyr::arrange)

In R:
```r
arrange(df, price)
```

**TODO:**  
1. Sort `df` by `price` (ascending)  
2. Sort `df` by `price` (descending)

In [ ]:
# Your code here
df.sort_values("price", ascending=False)

   price  size  bedrooms neighborhood  square feet
3  300.0  1800         4            B     6.000000
6  260.0  1700         4            B     6.538462
2  250.0  1600         3            B     6.400000
5  220.0  1550         3            B     7.045455
0  200.0  1400         3            A     7.000000
1  180.0  1200         2            A     6.666667
4    NaN  1500         3            A          NaN

In [ ]:
df.sort_values(["price", "size"])
#in this case, the data is first sorted by price, then by size

   price  size  bedrooms neighborhood  square feet
1  180.0  1200         2            A     6.666667
0  200.0  1400         3            A     7.000000
5  220.0  1550         3            B     7.045455
2  250.0  1600         3            B     6.400000
6  260.0  1700         4            B     6.538462
3  300.0  1800         4            B     6.000000
4    NaN  1500         3            A          NaN

## 7. Grouping and Aggregation

In R:
```r
df %>%
  group_by(neighborhood) %>%
  summarize(mean_price = mean(price, na.rm = TRUE))
```

**TODO:** Reproduce the summary above in pandas.

In [ ]:
# Your code here
df.groupby("neighborhood").agg(mean_price = ("price", "mean"), count = ("price", "count"))
#agg is the same as summarize in R
#count is the number of unique values that appear in each neighborhood

              mean_price  count
neighborhood
A                  190.0      2
B                  257.5      4

## 8. Method Chaining (Pipe Mindset)

Pandas supports method chaining, similar to `%>%` in R.

**TODO:** Using chaining, compute:
- **Filter:** `price > 200`  
- **Mutate:** `price_per_sqft = price / size`  
- **Group by** `neighborhood`  
- **Summarize:** average `price_per_sqft`

In pandas, the dot replaces the pipe operator

In [ ]:
(df.query("price > 200")
 .assign(ppsqft = lambda d: d.size/d.price))

   price  size  bedrooms neighborhood  square feet    ppsqft
2  250.0  1600         3            B     6.400000  0.080000
3  300.0  1800         4            B     6.000000  0.066667
5  220.0  1550         3            B     7.045455  0.090909
6  260.0  1700         4            B     6.538462  0.076923

## 9. Missing Data

**TODO:**  
1. **Identify** which values are missing  
2. **Drop** rows with missing values  
3. **Fill** missing prices with the mean price  

**Question:** When is dropping missing data reasonable? When is it risky?

In [ ]:
# Your code here
df.isna()

   price   size  bedrooms  neighborhood  square feet
0  False  False     False         False        False
1  False  False     False         False        False
2  False  False     False         False        False
3  False  False     False         False        False
4   True  False     False         False         True
5  False  False     False         False        False
6  False  False     False         False        False

In [ ]:
df.dropna(subset = ["price"])

   price  size  bedrooms neighborhood  square feet
0  200.0  1400         3            A     7.000000
1  180.0  1200         2            A     6.666667
2  250.0  1600         3            B     6.400000
3  300.0  1800         4            B     6.000000
5  220.0  1550         3            B     7.045455
6  260.0  1700         4            B     6.538462

In [ ]:
df.fillna(0)
#replace all NAs with 0

   price  size  bedrooms neighborhood  square feet
0  200.0  1400         3            A     7.000000
1  180.0  1200         2            A     6.666667
2  250.0  1600         3            B     6.400000
3  300.0  1800         4            B     6.000000
4    0.0  1500         3            A     0.000000
5  220.0  1550         3            B     7.045455
6  260.0  1700         4            B     6.538462

## 10. Common Pitfalls for R Users

- Boolean filtering requires **parentheses** when combining conditions.  
- `groupby()` does nothing until you **aggregate**.  
- Watch out for **chained assignment** warnings (use `.loc` or single assignment).

## 11. Active Learning Exercise (15–20 min)

**R pipeline:**
```r
df %>%
  filter(size > 1400) %>%
  mutate(price_per_sqft = price / size) %>%
  group_by(neighborhood) %>%
  summarize(avg_ppsqft = mean(price_per_sqft, na.rm = TRUE))
```

**TASK:** Translate the pipeline above into pandas using method chaining. Write clean, readable code.

In [ ]:
# Your solution below
(df
 .query("size > 1400")
 .assign(ppsqft = lambda d: d.price/d.size)
 .groupby("neighborhood")
 .agg(mean_ppsqft = ("ppsqft", "mean")))

              mean_ppsqft
neighborhood
A                     NaN
B                    10.3

In [ ]:
(df[df["size"]> 1400]
 .assign(ppsqft = lambda d: d.price/d.size)
 .groupby("neighborhood")
 .agg(mean_ppsqft = ("ppsqft", "mean")))

              mean_ppsqft
neighborhood
A                     NaN
B                    10.3

## 12. Wrap-Up Reflection

In 2–3 sentences:
- What feels **most similar** to dplyr?  
- What feels **most different**?  
- What do you find **confusing** so far?